@extends('admin.layouts.app')

@section('content')
    <div class="flex w-full flex-1 flex-col gap-6">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div class="space-y-1">
                <flux:heading size="xl" level="1">Add a color</flux:heading>
                <flux:text>Define a swatch that can be reused across the catalog.</flux:text>
            </div>
            <div class="flex flex-wrap gap-3">
                <flux:button variant="outline" :href="route('admin.colors.index')" wire:navigate>Back to colors</flux:button>
                <flux:button variant="primary" icon="check" icon:variant="outline" type="submit" form="color-form">Save
                    color</flux:button>
            </div>
        </div>

        {{-- <form id="color-form" class="rounded-xl border border-zinc-200 bg-white p-6 shadow-xs dark:border-zinc-700 dark:bg-zinc-900" method="POST" action="{{ route('admin.colors.store') }}">
            @csrf

            <div class="grid gap-4 sm:grid-cols-2">
                <flux:input name="name" label="Name" placeholder="E.g. Desert Sand" value="{{ old('name') }}" required />
                <flux:input name="slug" label="Slug" placeholder="desert-sand" value="{{ old('slug') }}" />
            </div>
            <flux:input name="hex" label="Hex code" placeholder="#1F2937" value="{{ old('hex') }}" />
            <flux:text variant="subtle" size="sm">Leave slug empty to auto-generate from the name. Hex values should start with <code>#</code> followed by 6 characters.</flux:text>
        </form> --}}
        <form id="color-form"
            class="rounded-xl border border-zinc-200 bg-white p-6 shadow-xs dark:border-zinc-700 dark:bg-zinc-900"
            method="post" action="{{ route('admin.colors.store') }}">
            @csrf
            <div class="grid gap-4 sm:grid-cols-2">
                <div>
                    <flux:input name="name" id="color-name" label="Name" placeholder="E.g. RED"
                        value="{{ old('name') }}" required />

                </div>
                <div>
                    <flux:input name="slug" id="color-slug" label="Slug" placeholder="red"
                        value="{{ old('slug') }}" />
                </div>

            </div>
            <div class="grid gap-4 sm:grid-cols-2 mt-6">
                <div>
                    <label for="hex" class="mb-1 block text-sm font-medium text-zinc-700 dark:text-zinc-200">
                        Hex Code
                    </label>

                    <div class="flex items-center gap-3">
                        <!-- Color Picker -->
                        <div class="relative">
                            <input type="color" id="color-picker" value="{{ old('hex') ?? '#1F2937' }}"
                                class="h-10 w-12 cursor-pointer appearance-none rounded-md border border-zinc-300 shadow-sm transition-colors hover:brightness-110 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-zinc-600 dark:bg-zinc-800 dark:shadow-md" />
                        </div>

                        <!-- Hex Text Input -->
                        <input type="text" name="hex" id="color-hex" placeholder="#1F2937"
                            value="{{ old('hex') ?? '#1F2937' }}"
                            class="flex-1 rounded-md border border-zinc-300 px-3 py-2 text-sm text-zinc-900 shadow-sm transition focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white" />
                    </div>

                    <p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                        Pick a color or enter a hex code manually (e.g., <code>#1F2937</code>)
                    </p>
                </div>
            </div>
            <flux:text variant="subtle" size="sm" class="mt-3">
                Leave slug empty to auto-generate from the name. Hex values should start with <code>#</code> followed by 6
                characters.
            </flux:text>

            <script>
                document.addEventListener('DOMContentLoaded', () => {
                    const nameInput = document.getElementById('color-name');
                    const slugInput = document.getElementById('color-slug');
                    const colorPicker = document.getElementById('color-picker');
                    const colorHex = document.getElementById('color-hex');

                    // Auto-generate slug from name
                    nameInput.addEventListener('input', () => {
                        if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                            const slug = nameInput.value
                                .toLowerCase()
                                .trim()
                                .replace(/[^\w\s-]/g, '')
                                .replace(/[\s_-]+/g, '-')
                                .replace(/^-+|-+$/g, '');

                            slugInput.value = slug;
                            slugInput.dataset.autoGenerated = 'true';
                        }
                    });

                    // Stop auto-generation if user edits slug manually
                    slugInput.addEventListener('input', () => {
                        slugInput.dataset.autoGenerated = 'false';
                    });

                    // Sync color picker to hex field
                    const syncColorToHex = () => {
                        colorHex.value = colorPicker.value;
                    };

                    // On color change or blur, update hex input
                    colorPicker.addEventListener('input', syncColorToHex);
                    colorPicker.addEventListener('blur', syncColorToHex);

                    // Sync hex input to color picker if valid
                    colorHex.addEventListener('input', () => {
                        const val = colorHex.value.trim();
                        if (/^#([0-9A-F]{6}|[0-9A-F]{3})$/i.test(val)) {
                            colorPicker.value = val;
                        }
                    });
                });
            </script>
        </form>
    </div>
@endsection
