@extends('admin.layouts.app')

@section('content')
    <div class="flex w-full flex-1 flex-col gap-6">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div class="space-y-1">
                <flux:heading size="xl" level="1">Edit color</flux:heading>
                <flux:text>Adjust the swatch settings below.</flux:text>
            </div>
            <div class="flex flex-wrap gap-3">
                <flux:button variant="outline" :href="route('admin.colors.index')" wire:navigate>Back to colors</flux:button>
                <flux:button variant="primary" icon="check" icon:variant="outline" type="submit" form="color-form">Update
                    color</flux:button>
            </div>
        </div>

        <form id="color-form"
            class="rounded-xl border border-zinc-200 bg-white p-6 shadow-xs dark:border-zinc-700 dark:bg-zinc-900"
            method="POST" action="{{ route('admin.colors.update', $color) }}">
            @csrf
            @method('PUT')

            <div class="grid gap-4 sm:grid-cols-2 mt-6">
                <div>
                    <label for="hex" class="mb-1 block text-sm font-medium text-zinc-700 dark:text-zinc-200">
                        Hex Code
                    </label>

                    <div class="flex items-center gap-3">
                        <!-- Color Picker -->
                        <input type="color" id="color-picker" value="{{ old('hex', $color->hex ?? '#1F2937') }}"
                            class="h-10 w-12 cursor-pointer appearance-none rounded-md border border-zinc-300 shadow-sm transition-colors hover:brightness-110 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-zinc-600 dark:bg-zinc-800 dark:shadow-md" />

                        <!-- Hex Input -->
                        <input type="text" name="hex" id="color-hex" placeholder="#1F2937"
                            value="{{ old('hex', $color->hex ?? '#1F2937') }}"
                            class="flex-1 rounded-md border border-zinc-300 px-3 py-2 text-sm text-zinc-900 shadow-sm transition focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white" />
                    </div>

                    <p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                        Pick a color or enter a hex code manually (e.g., <code>#1F2937</code>)
                    </p>
                </div>
            </div>
            <script>
                document.addEventListener('DOMContentLoaded', () => {
                    const nameInput = document.getElementById('color-name');
                    const slugInput = document.getElementById('color-slug');
                    const colorPicker = document.getElementById('color-picker');
                    const colorHex = document.getElementById('color-hex');

                    // Auto-generate slug from name
                    if (nameInput && slugInput) {
                        nameInput.addEventListener('input', () => {
                            if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                                const slug = nameInput.value
                                    .toLowerCase()
                                    .trim()
                                    .replace(/[^\w\s-]/g, '')
                                    .replace(/[\s_-]+/g, '-')
                                    .replace(/^-+|-+$/g, '');

                                slugInput.value = slug;
                                slugInput.dataset.autoGenerated = 'true';
                            }
                        });

                        slugInput.addEventListener('input', () => {
                            slugInput.dataset.autoGenerated = 'false';
                        });
                    }

                    // Sync color picker to hex
                    const syncColorToHex = () => {
                        if (colorPicker && colorHex) {
                            colorHex.value = colorPicker.value;
                        }
                    };

                    if (colorPicker && colorHex) {
                        colorPicker.addEventListener('input', syncColorToHex);
                        colorPicker.addEventListener('blur', syncColorToHex);

                        colorHex.addEventListener('input', () => {
                            const val = colorHex.value.trim();
                            if (/^#([0-9A-F]{6}|[0-9A-F]{3})$/i.test(val)) {
                                colorPicker.value = val;
                            }
                        });
                    }
                });
            </script>
            
        </form>
    </div>
@endsection
